openapi: 3.0.0
info:
  title: API Documentation
  description: >-
    Explore the API endpoints for a sample project, featuring examples to help
    guide you through their usage, all built according to OpenAPI v3
    specifications. This is a sample API descrition is used just for demo
    purposes.
  version: 1.0.0
  tags:
    - API
tags:
  - name: Example
    description: Operations related to example endpoints for demo.
paths:
  /example:
    post:
      summary: Create an example resource
      tags:
        - Example
      description: >-
        This is a sample description for the demo. Here you can write a short
        decription on what's the use of this API endpoint.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the example resource
                  example: Sample Name
                email:
                  type: string
                  format: email
                  description: User email (required)
                  example: user@example.com
              required:
                - name
                - email
      responses:
        "201":
          description: Resource created successfully
        "400":
          description: Invalid request body
